server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 200
      min-spare: 30
    connection-timeout: 5000ms
  port: 8080
  servlet:
    context-path: /modelRepository

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource